
# If you want to use your own database, set cloudnativepg.enabled to false.
# Then configure the enviroment variables by yourself in the nextcloud-env secret, the variables are:
# - POSTGRES_HOST
# - POSTGRES_PORT
# - POSTGRES_DB
# - POSTGRES_USER
# - POSTGRES_PASSWORD
cloudnativepg:
  enabled: true
  cluster: true
  databaseName: db
  databaseUser: nextcloud
  annotations: {}
  storage:
    storageClass: ""
    size: 10Gi

# Required environment variables to set manually:
# - REDIS_HOST
# - REDIS_PORT
# - REDIS_PASSWORD
redis:
  enabled: true
  persistence: false

# Nginx configuration
nginx:
  annotations: {}

# Required values
nextcloudDomain: &nextcloudDomain nextcloud.local
nextcloudImage: timpa0130/nextcloud-k8s
nginxImage: timpa0130/nextcloud-k8s-nginx
nextcloudImageTag: 20250707-1606
nginxImageTag: 20250629-1552

# Openshift compatibility
openshiftCompatibility: false

# Nextcloud configuration
nextcloud:
  caCertificates:
    enabled: false
    configMapName: ca-bundle
  objectStorage: false
  annotations: {}
  # Replaces the trusted_domains in the nextcloud config.php
  trustedDomains: # Required
    - *nextcloudDomain
    - localhost
  # Replaces the trusted_proxies in the nextcloud config.php
  trustedProxies:
    - 10.0.0.0/24
  # Redis is required to handle sessions for nextcloud to work with more than one instance.
  replicaCount: 1
  # Configure the certificate for the ingress outside of the chart.
  ingress:
    enabled: true
    # Configure the ingress tls cert through cert-manager annotation
    annotations: {}
    tlsSecretName: ""
  storage:
    storageClass: ""
    size: 10Gi
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "1500m"
      memory: "1024Mi"

