apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-php
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/5  *  *  *  *"
  jobTemplate:
    spec:
      template:
        spec:
          concurrencyPolicy: Forbid
          restartPolicy: Never
          {{- if .Values.openshiftCompatibility }}
          serviceAccountName: nextcloud
          automountServiceAccountToken: false
          {{- else }}
          automountServiceAccountToken: false
          {{- end }}
          securityContext:
            runAsUser: 33
            runAsGroup: 33
            fsGroup: 33
          containers:
          - name: cron-php
            image: {{ .Values.nextcloudImage }}:{{ .Values.nextcloudImageTag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              php -f /var/www/html/occ status -e && \
              php -f /var/www/html/cron.php
            volumeMounts:
              {{/* Folders with persistent data */}}
              - name: nextcloud-data
                mountPath: /mnt/ncdata
                subPath: ncdata
              - name: nextcloud-data
                mountPath: /var/www/html
                subPath: html
              {{/* php config files */}}
              {{- range $path, $content := .Files.Glob "files/php-config/*" }}
              - name: nextcloud-php-config
                mountPath: /usr/local/etc/php/conf.d/custom-{{ base $path }}
                subPath: {{ base $path }}
              {{- end }}
              {{- if .Values.nextcloud.caCertificates.enabled }}
              - name: ca-bundle
                mountPath: /etc/ssl/certs/ca-certificates.crt
                subPath: ca-bundle.crt
              {{- end }}
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: nextcloud-data
            - name: nextcloud-php-config
              configMap:
                name: nextcloud-php-config
                defaultMode: 420
            {{- if .Values.nextcloud.caCertificates.enabled }}
            - name: ca-bundle
              configMap:
                name: {{ .Values.nextcloud.caCertificates.configMapName }}
                defaultMode: 420
            {{- end }}
