---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.nextcloud.storage.storageClass }}
  storageClassName: {{ .Values.nextcloud.storage.storageClass }}
  {{- end }}
  {{- if .Values.nextcloud.storage.accessModes }}
  accessModes:
    {{- toYaml .Values.nextcloud.storage.accessModes | nindent 4 }}
  {{- else }}
  accessModes:
    - ReadWriteMany
  {{- end }}
  resources:
    requests:
      {{- if .Values.nextcloud.storage.size }}
      storage: {{ .Values.nextcloud.storage.size }}
      {{- else}}
      storage: 10Gi
      {{- end }}
