---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $content := .Files.Glob "files/nginx/*" }}
  {{ base $path }}: |
{{ tpl ($content | toString) $ | indent 4 }}
{{- end }}