---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCMIteeRTORSI8WnwMBnSD16EMYfvW6uBQ05/qm+y/TXK6xPp6up0C82HxCyxrF8YpeUGSmoH8a30epE2FZBI0GFQFUDADk2mbVADAw6qKA/VAA1G0lSmXzjqyE3cBSPFHZhWDKpmKhxJGY51nvYP8BDjd8/ukGAbE7QtYtrokUmYIswISNW6UVhA7GwpNgFFHhupSagd4NjZ/Y6+dh8UtHp5gnK2iZG/ekL6F6RxX1C7O5i05s1KllpgqUMZ9cD1xFUe3IRISAdofTMXq62/rIokRcPg/L8LN4Sx2Z5O98RnIWTf/SHEVFmOR6oQYnHioMetPaBTNYDr8k4wZtaCn9a+eddrvYu7AjUK9uCDjlbU6R9fqC6Er669K9Hg0Ah+snzc+L/hDNsouaeUIo0G0kbOScXySRbUFZ0tAzMAkFA5IYDGakYEJiEl8LmNWimpX2vp6wdbBxBPQLPn3BcT9AHMg2uQZAKiDMVX7QGG/CMD7wvP0PgmtwD3Rykgy3dO5APKucvHGGAoDVWsvJZkwvthGVxDBA2zkYRmvxVgwPlUB623goNjJ2XVk5EAbDqPEOgBQRj9N5BOtBz/kkY8TA3wAJ32R8qpweO9fFlhQg1/5gufTw3kY/OcKfUkn0tTQpZKmbnGwJPg7APhheE//N00DXoETRd11joDGm+1h4SYi/kPDnDKp4rxVaA01sUDY+cBmJIo+GUGTj6ZUOASsO2rmEFOYxBQF89pWawHTaLcoGJIR9fvDp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
