---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBaklIJNiqp0FwsghTbfEIpuNq16kCtzF1fQQwnE40ScC1UQx4zrhS4GDh2BOom5qb8d48+i3qinsbFHAt2s+eLmeIa4KPWvjC4ZCf5b1TOuq9Jr2zDqYuk990KkdAkV3ju+XZI9cVlogvrvsostGY9z5vN2Vczde+Xd/HsgwOJcW6Cj6cokWkBDIQiunOJE7fZ6X3Ybnbw98V+jUZtKce8Mlvoce1YekH6mYBAE1bOp8iXTUnYh7jj+7Q0CDR2aSFKNykxxNgZ1S+CuXd/fJ2GEq4yjJ/eJM4ZLq2d6VNxbtkWxgwQvlnrcD3r6Lx4GyHghZxcYYsdll2VjYf0OxnDXXkpVAnhB+fUBkQQvNVnBZv5PWa9lKIBSnzEH8kYeJz5r1yIHfmXprPJDCDKjFd1GWoPCF2RvKDOf92jcI8nxL07lZcREq4Swf8fsBRZaPKVvQkNJPP1KC16IbTRNTkxGyVbkc8hYbZbrFRZSBoORsABkcCvTQHev1XmDNAzA9Qusa/xzEsS5HInE1NYDypfdHXsijDWJI6qCq+Jb0YCsO4ChP9HJWFgAuXbBr3a91WliJOAMiR0FdESvV1Hsn0K8szXdJwf6yIyg2O4bBqLl+p5TsH5Uc+BAu2XNVaqrwimueSjZ5m9qCvjUwU3JpxrYyGAasn2MQEbqA/TdYEFPdmURxLqPtc7Qvg9mQRybgjhspH/zOY7ID7kJq2rHj2XJyBKeXB326vMTy0OdLgq4dBSDujkiclr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
