---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-user
  namespace: nextcloud-s3
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgBc4brUBZ7noU/CxnL3+wzCl/s7B8ff5mtKEWI7aQCdYcIwRa+y17zMapl/J4JW+blc5gYUodq/J5n3HaOddy9xzAKEV3d2rqzDdKPut1Pj4gJHchajL+p4i1vBA4fv3fi54/PuyLO4/ChQIuLsKiHPr3kW1+gATDJS/OL3SKfCnf0CLZ7RuAwRXo3la1nFJhMqRmvV5sV99ENh1+4w5KQ/E5XFKyENyl5I7NlTL0+CAwiNhzDIDgyjPRc9/bPirY0GY5u2d/dyAwSqpLkaCJn1/U7cypWld6OlncouARTyRJjuxPZsaiIa6O57KeDfMvXRLdvYk/DmMp8au38hN6+TfH6LsvNqFoHZd+DwTDUH+P2QzUYbq8KANNP8MEUfy3nS9519lGtPJa87UHF3JowtXC4/9NdiFcyWqPiCsgAalz4hndyJIMHhN9NZZxDQuRrlHW9N7kEyIhbbBzX93RYzbiwIu6mRZyS6dY52cxmCEvO67ozEJjDtWWZpaAYxjr5eIzxQfDjrk28/gSv1DC9B7NABV7kG1/MVqAC5F0pMzmBWvoQFTJ94Z9mqMVOa/M7+2mDCuDbpCGXsclsbRwhV2ekO6aZqcXy+pgJ65KRaqarI02Tfs3HEbhUzY2naKHwLPOxIj1KK7ZcJ7GFTsNGq70yoCccKb5tEGifxTzuaZJ57u0umtqLSt6qmUTD+w1ah7bSoQPLXcnY=
    CONSOLE_SECRET_KEY: AgCyoUK5+f9De6ixr6o/Ag9CElDmOeRbZzvRgokn0cJnOHWJv4wDTPbFCRDLp8yNynRKTtsykfCDsir75l+bQKAxFh/t6qaLZftFcCgXh0jPgPFKayjKGF6z3UdJvoVCsXjpesPe4/z2DS4GydhPOCKkWU+S1vzCNWvlNKLoDttRmkOv3gEnZWkDN++kRziUae3xFnRg3/I7xTPo7TP1drX3HUHQjkqp0WOW0gKvQYqMgV/DHIFrTuK7aimY3RqKXGL7VzQddypUviEv9pT69nBwqz+azW+fFkPDZia9Yu7/AVVOmDr27D0chg4yW8LWs7TwkQFThYicch1cNMXM2mENtom/pAaYMqEYZ6t8Z199f1bPjq/XowuQarGsWHJVtNXq1smHg3UewvGDVNUt0Kz/6l3QTBZVgmx63m4kMIsJL85BMTQvG2xyNryrwsFcNCPjxOp38yaGJAFsGnjF9ZUyEAU71fjLYoYz1Ct545fXLtADhkWoYrrsijmVAgeWbLL0oFFG5zEML3Whh0CX3prGc08hgPRkSE5PXneBquQHOo2nc25PcXtkr0QyeJa4qJl1c5tvnPSbmqgN668xaswoP98FNcLQ71CAc2SDgP+xfwgTa0J5YGvpTPMzK14CdHGipEM55PHcoy6vavaNnbWg0RgqEBqIoygLNCdxYtIR+05XknU6czwVuL9N53v1xmTTdUecqTCC58htNrs=
  template:
    metadata:
      creationTimestamp: null
      name: minio-user
      namespace: nextcloud-s3
    type: Opaque
