---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-environment
  namespace: nextcloud-s3
spec:
  encryptedData:
    config.env: AgCQZif8XnrwqxUnJE4CsSJCXtz5parl+K+nHVD2CEV3fhhRfvor4oJlkBWcMa53ZmyIp6akIodUiNCvvJ2Sc+pdVNYUBarnBojPM744wDrBS7U+QMla/5+3BbjCOXNdqEbXKnl8ww/bbpdKWygv0L1sSx9TLqcPt+i6R+9IT4Wa0/sBe9Kb9W3GdMkrqW12IbNxREeJ/06kdC9kaRHVSc1mlgPGWbVkP4FuKJtryY8wGq5RZYVB5jSJdS7/Gf81v4QvBQQ6YIQKsFXsJuQzMIlZ3+LblqrLtJepHSWgdVHJ4B/t+wVVRNX/RicwGQH4q+2yyX/2ERxCBCUuB3a5MZgWddgitDRNthGpKdpmrXylpaUJJSQWtPpaxrGkMva5qfAoMVJc7VxqjwtCNcCW9Cw8mBIj8Yb4Trre9rgWsnXLLtBeALe5EkkPTwX392jL9m9vsoiBClvAmGp2+WSI+5kcGUJhGcHjt+DBsmz65m1i7Fisgi/0QrJKtsTWhXfQD6VO0TRgCxPzMaY2Gg4K4/u7QzT4I9Vzprneq/wbF5Wp93mW3kLivEW7ahbDMk5upm0q34gX/AFaklveZYXr/fORo4r5FXYr8x0Aq4uGd0lJfz4r9CurEJ5wZGzjqyU430TgtDujOauEUs7Ceg5WXUxH0bYGKxEgxaP2NisYgtY9fp2VmN4ABUq87X8ymApshqr0a2YQ95zftj7ESiGlD7dUP9vTPPdriGT0+U4RV8BKdbdcTV0C3c6hOMo8BL2wBFUE0wAO26SbsSLCAEyaSdTJ9VHv6tvoCrCnAzLkD8yUDv5bCDM7A28uTK6FZl8XTg/xEOJNmmNQUDrAxjJ1y2qY+twmnpNDh6FJIVau1wRI9L1r6/XVu2eZcQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-environment
      namespace: nextcloud-s3
    type: Opaque
