---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: nextcloud
spec:
  encryptedData:
    .dockerconfigjson: AgA1UxyyIwf7Z3A08Z8q9gw/R64hF/7k89jEC+LuF+cvo0XxOVhTZc5itgXOMScOiPZUMwhbDBaSJ+N1qU8XMTDiie4YmapZjjHDeqTKdgKxYEZRWIjWhTlpVd/TpoEdrSuTbIc/D+/dQfWGQeC8ZO1eQWI0kbkrBJNU1aX2fFuBLO1EgYczQztcOCFr+O73/ov0F70VFyr09MFx7F00mW4yHLlEcQkLt/O3LTaPwjrShriOSzdK6gNe9Vxa3QF+jsh13lN4hQUUUqLe7QO7Kg3ypgIFjBn7BMbTuG61PUJG9lxDA9DEZcLKQ8Csi1TY7ecWvijRMLMYcUPlFpwE48iDNioYHyRIm4RlQdj4337FFg3B/1f6qeqtBgtubb7QDwLiHdXR9FR6Y9Z4MlTbDP13i+WV+yFJkG7Gy1aS9ZWmdMQIItKGTNad8PxaLgvspJPkrSLeSoCSRjxlAStB/LJCsD0t/jjC3l6FIfdiZjWdzkHtgQUPagmZiPr8ktHxX8FgYiIe8fJCF4KkbCPCp2l8CNFNL5U5f0KxKF013fLjqEc651DptK3BV5CZVZLN1I8WmLnyVXLAs7dkloRw2RI31Za43SKS0JdBslxHLOmpWaYJVgPGozH9d9jU6fLqRLzTT4JWF973niAGy7H2kWCG4yxaPWMkQBdvPp3hY7ttr2VKJgLDJCKqi27jzZFkegeGfILDg3uCDVokKRTSRnX6YcwOjV/soNcF7REfNgX1XKgkgPcC1q7sC9RVdhiEnEyvKXzpqvFjUBXdgoKFsEwW/OXJCBm20yvidCcPHVwjB3VmYKgoBPh/l8p2SoFBRWf+YWD4LH9uiTsMM2jy7g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: nextcloud
    type: kubernetes.io/dockerconfigjson
