---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: nextcloud-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - {{ .Values.nextcloudDomain }}