name: Build Nginx Image

on:
  push:
    branches: [main]
    paths:
      #- chart/templates/nginx-deploy.yaml
      - .github/workflows/build-nginx-image.yaml

env:
  NGINX_IMAGE: timpa0130/nextcloud-k8s-nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: nginx/docker-nginx-unprivileged

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: timpa0130
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate name for image
        id: image-name
        run: |
          echo "latest=docker.io/${{ env.NGINX_IMAGE }}:latest" >> $GITHUB_OUTPUT
          echo "date=docker.io/${{ env.NGINX_IMAGE }}:$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.image-name.outputs.latest }},${{ steps.image-name.outputs.date }}
          context: stable/alpine
          file: stable/alpine/Dockerfile
          build-args: |
            UID=33
            GID=33
