name: Build Nextcloud Image
on:
  pull_request:
    branches: [main]
    paths:
      - image/Dockerfile
      - image/files/install.sh
      - image/files/entrypoint.sh
      - .github/workflows/build-nextcloud-image.yaml
  push:
    branches: [main]
    paths:
      - image/Dockerfile
      - image/files/install.sh
      - image/files/entrypoint.sh
      - .github/workflows/build-nextcloud-image.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: timpa0130
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate name for image
        id: image-name
        run: |
          echo "latest=docker.io/timpa0130/nextcloud-k8s:latest" >> $GITHUB_OUTPUT
          echo "date=docker.io/timpa0130/nextcloud-k8s:$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.image-name.outputs.latest }},${{ steps.image-name.outputs.date }}
          context: image
          cache-to: type=registry,ref=timpa0130/nextcloud-k8-cache:latest
          cache-from: type=registry,ref=timpa0130/nextcloud-k8-cache:latest
